### ISSUE TITLE
Not seeing data in ES

### ISSUE THREAD

**Issue by DigiAngel** [dunbarcyber/cyphondock#15]
So I've followed the tutorial almost to the letter, save a couple tweaks.  As I am not using Beats, but using rsyslog from a remote device.  The input is:
~~~
input {
        tcp {
                type => "snort"
                port => 5504
        }
~~~

second, I'm using snorts fast file format, not the syslog format so the grok is different for ts:
~~~
if [ts] {
         date {
                  match => [ "ts", "MM/dd-HH:mm:ss.SSSSSS" ]
                  target => "sys_timestamp"
         }
}
~~~

other than that it's got all the info from the tutorial.  However the cyphon index never gets created on testing.  I've packet captured on the cyphon box and I see packets coming in.  Netstat shows:
~~~
tcp6       0      0 :::5044                 :::*                    LISTEN      28942/docker-proxy
~~~

docker ps -a shows:
~~~
docker.elastic.co/logstash/logstash:5.3.2             "/usr/local/bin/do..."   40 minutes ago      Up 8 minutes        0.0.0.0:5044-5045->5044-5045/tcp, 9600/tcp
~~~

My main question is, in this docker environment especially, how do I troubleshoot this?  Usually I'd set my output in logstash.conf with:
~~~
stdout { codec => rubydebug }
~~~
which I tried but I did not notice any changes when I ran sudo docker-compose up and watched the logs.  Still though, kibana shows nothing matching cyphon-* or logstash-*:
![2017-05-25 12_41_19-generating alerts from logstash output cyphon 1 1 2 documentation](https://cloud.githubusercontent.com/assets/947191/26472457/6a7f1c30-4163-11e7-832a-d20737395562.jpg)

Thank you.

**Comment by lhadjchikh** [comment]
Logspout captures stdout from any container that doesn't have this setting in Docker Compose:
```
 can check logs from the most of the containers by searching logspout-* in Logspout, assuming you've got a Logspout container running. You can also check your RabbitMQ management dashboard to see if you have a queue called "watchdogs" with some queue consumers. The RabbitMq dashboard should be on port 15672 when running with production configs. Are you running all the Cyphondock containers?

**Comment by lhadjchikh** [comment]
Sorry, my last comment got posted before I was ready, but I tried to edit it. :-) Anyway, the output from `stdout { codec => rubydebug }` is probably being captured by Logspout, so check under that logspout-* index in Logstash.

**Comment by lhadjchikh** [comment]
Oh, and if you're sending input to port 5504 as shown above, you'll need to expose that port on your Logstash container in the `docker-compose.override.yml` file, e.g.:
```
  logstash:
    ports:
      - "5044:5044"
      - "5045:5045"  # you can configure Filebeat to send Nessus files here
      - "5504:5504"
```

**Comment by DigiAngel** [comment]
Thank you.  So yea...I started this post with 5504 and found that error and fixed it and forgot to change it here..go me!  I don't think I watchdogs is running:
![2017-05-26 09_00_42-rabbitmq management](https://cloud.githubusercontent.com/assets/947191/26500070/e7c265d8-41f1-11e7-8dbe-3b0bd85bb8ff.jpg)
would not having this watchdog impact not getting data into ES?
![2017-05-26 09_03_13-console - kibana](https://cloud.githubusercontent.com/assets/947191/26500166/2e54a448-41f2-11e7-886a-f6d3449e23d8.jpg)
I'll try the rubydebug and check again...I'll report what I find here thank you.

**Comment by lhadjchikh** [comment]
"Idle" is okay; it only says "running" if it's actually processing a message. Click on "watchdogs" and see how many queue consumers there are, though. You need at least one to generate alerts. You should still be getting data into ES either way, though.

**Comment by lhadjchikh** [comment]
Do you have a closing bracket on your Logstash input, above? Just checking. :-)

**Comment by DigiAngel** [comment]
Thanks....I have 1 watchdog consumer.  And yes on the bracket..that's a good check.  I see no debug though from logstash after ctrl-c and then sudo docker-compose up.  In kibana I have logspout-* and I see no debug there either.  The last bit I guess I can include is the grok line.  This is taken from a current working ELK stack:
~~~
filter {
        #snort
        if [type] == "snort" {
                grok {
                        #normal
                        match => [ "message", "%{DATA:date}  %{DATA:junk} \[%{INT:gid}\:%{INT:sid}\:%{INT:rev}\] %{DATA:ids_alert} (?<junk>\[\*\*\]) \[Classification\: %{DATA:ids_classification}\] \[Priority\: %{INT:ids_priority}\] \{%{WORD:proto}\} %{IP:src_ip}\:%{INT:src_port} \-\> %{IP:dst_ip}\:%{INT:dst_port}" ]
                        #portless
                        match => [ "message", "%{DATA:date}  %{DATA:junk} \[%{INT:gid}\:%{INT:sid}\:%{INT:rev}\] %{DATA:ids_alert} (?<junk>\[\*\*\]) \[Classification\: %{DATA:ids_classification}\] \[Priority\: %{INT:ids_priority}\] \{%{WORD:proto}\} %{IP:src_ip} \-\> %{IP:dst_ip}" ]
                }
                uuid {
                        target => "@uuid"
                }
                mutate {
                        add_field => {
                                "collection" => "elasticsearch.cyphon.snort"
                        }
                }
                        if [ts] {
                                date {
                                match => [ "ts", "MM/dd-HH:mm:ss.SSSSSS" ]
                                target => "sys_timestamp"
                                }
                        }
                }
        }
}

**Comment by lhadjchikh** [comment]
Not sure this is the problem, but it looks like there's an extra bracket that should be removed:
```
filter {
        #snort
        if [type] == "snort" {
                grok {
                        #normal
                        match => [ "message", "%{DATA:date}  %{DATA:junk} \[%{INT:gid}\:%{INT:sid}\:%{INT:rev}\] %{DATA:ids_alert} (?<junk>\[\*\*\]) \[Classification\: %{DATA:ids_classification}\] \[Priority\: %{INT:ids_priority}\] \{%{WORD:proto}\} %{IP:src_ip}\:%{INT:src_port} \-\> %{IP:dst_ip}\:%{INT:dst_port}" ]
                        #portless
                        match => [ "message", "%{DATA:date}  %{DATA:junk} \[%{INT:gid}\:%{INT:sid}\:%{INT:rev}\] %{DATA:ids_alert} (?<junk>\[\*\*\]) \[Classification\: %{DATA:ids_classification}\] \[Priority\: %{INT:ids_priority}\] \{%{WORD:proto}\} %{IP:src_ip} \-\> %{IP:dst_ip}" ]
                }
                uuid {
                        target => "@uuid"
                }
                mutate {
                        add_field => {
                                "collection" => "elasticsearch.cyphon.snort"
                        }
                }
                if [ts] {
                        date {
                        match => [ "ts", "MM/dd-HH:mm:ss.SSSSSS" ]
                        target => "sys_timestamp"
                        }
                }
                
        }
}
```

**Comment by DigiAngel** [comment]
It's not...I added them in to make sure it looked good ;)  Truth be told there are several other entries.  I guess I'll bite the bullet and just delete everything besides the snort stuff and post here.  Danke!

**Comment by lhadjchikh** [comment]
Yeah, I figured Logstash would have told you if that had been the case, but thought I'd ask.

If you haven't already, you can add this to your Logstash service in `docker-compose.yml`:
```
    environment:
      LOGSPOUT: ignore
```
That will at least take Logspout out of the picture while you're debugging.

**Comment by DigiAngel** [comment]
Thanks....I get an error with that however.  Also...do you folks plan on releasing a non-dockerized version of this as well?

![2017-05-26 09_53_51-siemdev](https://cloud.githubusercontent.com/assets/947191/26502241/41db72b0-41f9-11e7-9d62-4f1ea609c4d4.jpg)
![2017-05-26 09_53_41-siemdev](https://cloud.githubusercontent.com/assets/947191/26502243/4660b156-41f9-11e7-8935-a1decef1dbbe.jpg)

**Comment by lhadjchikh** [comment]
The `LOGSPOUT` line needs to be indented 2 spaces. YML is very picky about indentation. :-)

We're working on a VM right now, but we need to develop some automation for that, so I'm not sure how soon it will be out. If you already have an ELK stack running, you can just install the other components (RabbitMQ and PostgreSQL) and deploy it without Docker. I have some instructions for CentOS, but I need to update them. Most of the settings you'd need to change are in the `cyphon/settings/conf.py` file (where you specify your Elasticsearch server, etc.).

**Comment by DigiAngel** [comment]
LoL....ok thanks.  Yea if you have any resources for deploying on an already established ELK stack that would be awesome.  I LOVE docker's ability to get up and running quickly, but my perception is that it's getting in the way of troubleshooting in this case, and if I decide to use Cyphon in production, I wouldn't use it in a docker instance anyway.  I'll make the correction and continue on..thanks for your help and patience.

**Comment by lhadjchikh** [comment]
No worries, I've tripped up on the same things myself. I'll work on updating my old instructions and let you know when they're online!

**Comment by DigiAngel** [comment]
Ok that fixed it up.  I get nothing from logstash however.  I think I'll wait to install this without docker.  Thanks so much!
