### ISSUE TITLE
Snort Tutorial Question from http://cyphon.readthedocs.io/

### ISSUE THREAD

**Issue by hotsauce-v2** [dunbarcyber/cyphondock#23]
I have followed the extremely well developed and helpful guide on readthedocs to install using docker-compose. Working through the Snort tutorial using filebeat and logstash, at this point: http://cyphon.readthedocs.io/en/latest/tutorials/logstash-tutorial.html#step-2-logstash

Where is the logstash conf file located to add?

input {
    beats {
        port => 5044
    }
}

Do we place it in the /opt/cyphon/cyphondock/config/logstash directory under pipeline or config?

Thanks again for the hard work.

**Comment by lhadjchikh** [comment]
Sorry, I should clarify that in the docs! The Logstash input file is this one: https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/1-input.conf

if you copied the `config-COPYME` directory, you should already have it, and the Logstash container will load the pipeline files when it starts up: https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.yml#L116-L120

**Comment by hotsauce-v2** [comment]
Okay perfect. Thank you @lhadjchikh My end goal is to use this to ingest vulnerability scan results from Nessus. Learning as I go, your docs have been pivotal.

**Comment by lhadjchikh** [comment]
Thanks, that's great to hear! We're still trying to improve the docs, so if anything is unclear, please let us know!
