### ISSUE TITLE
Kibana Server Error 500 

### ISSUE THREAD

**Issue by kxuanCeltik** [dunbarcyber/cyphondock#30]
Hi,

When I launch and try to go kibana ( localhost:5601 ) it answer with a error 500, in both, .ova and cyphondock.

What is the problem?

Thanks

**Comment by censey** [comment]
This would be worth reviewing.  May not be the same issue on your installation:

https://github.com/dunbarcyber/cyphon/issues/183

**Comment by lhadjchikh** [comment]
Yes, as @censey said, it's likely an issue with the container start up order, so you can try to restart the problem containers as @darvid suggested in https://github.com/dunbarcyber/cyphon/issues/183:
```
$ docker-compose restart elasticsearch
$ docker-compose restart kibana
$ docker-compose restart nginx
```
I've also found that I often have to wait quite a while (many minutes) for the Kibana page to work when starting a fresh instance (I think it may be waiting for Elasticsearch indexes to be ready). So you might try it again after 5-10 minutes or so.

**Comment by kxuanCeltik** [comment]
I try to restart in this order and the same error. I wait and nothing.

**Comment by censey** [comment]
I am assuming you are using the latest 1.4.1 build?

**Comment by lhadjchikh** [comment]
Are you getting any info from the Kibana container logs?

```
$ docker-compose logs -f kibana
```

**Comment by censey** [comment]
If you aren't getting any logs, please provide any additional details you can about the host you are running on?  How much ram is available, what OS, etc.  Are you able to access the main Cyphon logon page?

**Comment by kxuanCeltik** [comment]
`kibana_1         | {"type":"log","@timestamp":"2017-08-23T14:40:12Z","tags":["status","plugin:elasticsearch@5.3.2","error"],"pid":7,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}`

Maybe would be because X-pack.

I try in 1.4 and in master.

**Comment by kxuanCeltik** [comment]
Yes, I access to cyphon logon page.

Hardware no problem because is 8 CPU and 32 RAM on Ubuntu 16.

**Comment by lhadjchikh** [comment]
Do you have `xpack.security.enabled: false` set in your `elasticsearch.yml` and `kibana.yml` files?

**Comment by darvid** [comment]
It looks like it can't connect to Elasticsearch, could you run ``docker-compose logs -f elasticsearch`` and paste some of the output? It's possible that Elasticsearch is taking a long time to start, or failing to start and constantly restarting.

**Comment by kxuanCeltik** [comment]
` org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to created node environment
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to created node environment
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	... 6 more
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1  | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch_1  | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch_1  | 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_121]
elasticsearch_1  | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_121]
elasticsearch_1  | 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_121]
elasticsearch_1  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:262) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  | 	... 6 more
cyphondock_elasticsearch_1 exited with code 1
`

**Comment by darvid** [comment]
Could you please do a ``ls -l`` of the ``/opt`` directory on your host (the VM or wherever you're running Cyphondock from)? I suspect the data directory that's configured in ``docker-compose.override.yml`` for Elasticsearch has the wrong permissions.

**Comment by kxuanCeltik** [comment]
My /opt is of root.

But I don't know where is the data directory of elasticsearch, is:
`/usr/share/elasticsearch/data/nodes`

/usr/share is also of root.

But I also try to execute `sudo docker-compose up`

**Comment by lhadjchikh** [comment]
The elasticsearch volume on the VM is defined here: https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.override.yml#L13

**Comment by darvid** [comment]
Could you try running ``chown -R 1000:1000 /opt/data`` and restarting the Elasticsearch container? Assuming that's where your data directory is. The problem I believe is that the Elasticsearch docker container user is uid 1000, so it can't write to ``/opt/data`` which is owned by root.

**Comment by kxuanCeltik** [comment]
Yes, it was a permissions issue.

Thanks a lot.

I also have permissions problems with filebeat.yml

**Comment by lhadjchikh** [comment]
Sorry, see if this fixes it (assuming you're in the `cyphondock` directory):
```
sudo chmod go-w config/beats/filebeat
```

**Comment by kxuanCeltik** [comment]
Yes, this fix it.

Thanks

**Comment by robinlennox** [comment]
I think it's better to set the permission on the actual folder as such:
sudo chown -R 1000:1000 /opt/cyphon/data/elasticsearch
