### ISSUE TITLE
Mailbox adding - server error 500

### ISSUE THREAD

**Issue by suchandbabu** [dunbarcyber/cyphondock#37]
Hi,
I am trying to create a new mailbox in the below format.
imap+ssl://youremailaddress%40gmail.com:1234@imap.gmail.com?archive=Archived

but its getting a server error 500 . How can i resolve this.

**Comment by lhadjchikh** [comment]
Assuming you're running Docker containers, can you check the logs of the Nginx and Cyphon containers to see if you can find more info on the error? You can try these commands from the `cyphondock` working directory:
```
docker-compose logs -f nginx
docker-compose logs -f cyphon
```

**Comment by suchandbabu** [comment]
Thanks for your reply.

docker-compose logs -f cyphon
cyphon_1         | SyntaxError: invalid syntax
cyphon_1         | [2017-10-17 07:51:39 +0000] [26] [ERROR] Exception in worker process
cyphon_1         | Traceback (most recent call last):
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
cyphon_1         |     self.wsgi = self.app.wsgi()
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
cyphon_1         |     self.callable = self.load()
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
cyphon_1         |     return self.load_wsgiapp()
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
cyphon_1         |     return util.import_app(self.app_uri)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
cyphon_1         |     __import__(module)
cyphon_1         |   File "/usr/src/app/cyphon/cyphon/__init__.py", line 21, in <module>
cyphon_1         |     from .celeryapp import app as celery_app
cyphon_1         |   File "/usr/src/app/cyphon/cyphon/celeryapp.py", line 33, in <module>
cyphon_1         |     app = Celery('cyphon', broker=settings.BROKER_URL, include=['cyphon.tasks'])
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
cyphon_1         |     self._setup(name)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
cyphon_1         |     self._wrapped = Settings(settings_module)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
cyphon_1         |     mod = importlib.import_module(self.SETTINGS_MODULE)
cyphon_1         |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
cyphon_1         |     return _bootstrap._gcd_import(name[level:], package, level)
cyphon_1         |   File "/usr/src/app/cyphon/cyphon/settings/prod.py", line 21, in <module>
cyphon_1         |     from .base import *
cyphon_1         |   File "/usr/src/app/cyphon/cyphon/settings/base.py", line 23, in <module>
cyphon_1         |     from .conf import *
cyphon_1         |   File "/usr/src/app/cyphon/cyphon/settings/conf.py", line 19
cyphon_1         |     'ALLOWED_HOSTS': [*],
cyphon_1         |                        ^
cyphon_1         | SyntaxError: invalid syntax
cyphon_1         |
cyphon_1         | During handling of the above exception, another exception occurred:
cyphon_1         |
cyphon_1         | Traceback (most recent call last):
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
cyphon_1         |     worker.init_process()
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
cyphon_1         |     self.load_wsgi()
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 148, in load_wsgi
cyphon_1         |     self.reloader.add_extra_file(exc_val.filename)
cyphon_1         | AttributeError: 'NoneType' object has no attribute 'add_extra_file'
cyphon_1         | Traceback (most recent call last):
cyphon_1         |   File "manage.py", line 26, in <module>
cyphon_1         |     execute_from_command_line(sys.argv)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
cyphon_1         |     utility.execute()
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
cyphon_1         |     settings.INSTALLED_APPS
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
cyphon_1         |     self._setup(name)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
cyphon_1         |     self._wrapped = Settings(settings_module)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
cyphon_1         |     mod = importlib.import_module(self.SETTINGS_MODULE)
cyphon_1         |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
cyphon_1         |     return _bootstrap._gcd_import(name[level:], package, level)
cyphon_1         |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
cyphon_1         |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
cyphon_1         |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
cyphon_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
cyphon_1         |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
cyphon_1         |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
cyphon_1         |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
cyphon_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
cyphon_1         |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
cyphon_1         |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
cyphon_1         |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
cyphon_1         |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
cyphon_1         |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
cyphon_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
cyphon_1         |   File "/usr/src/app/cyphon/cyphon/__init__.py", line 21, in <module>
cyphon_1         |     from .celeryapp import app as celery_app
cyphon_1         |   File "/usr/src/app/cyphon/cyphon/celeryapp.py", line 33, in <module>
cyphon_1         |     app = Celery('cyphon', broker=settings.BROKER_URL, include=['cyphon.tasks'])
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
cyphon_1         |     self._setup(name)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
cyphon_1         |     self._wrapped = Settings(settings_module)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
cyphon_1         |     mod = importlib.import_module(self.SETTINGS_MODULE)
cyphon_1         |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
cyphon_1         |     return _bootstrap._gcd_import(name[level:], package, level)
cyphon_1         |   File "/usr/src/app/cyphon/cyphon/settings/prod.py", line 21, in <module>
cyphon_1         |     from .base import *
cyphon_1         |   File "/usr/src/app/cyphon/cyphon/settings/base.py", line 23, in <module>
cyphon_1         |     from .conf import *
cyphon_1         |   File "/usr/src/app/cyphon/cyphon/settings/conf.py", line 19
cyphon_1         |     'ALLOWED_HOSTS': [*],
cyphon_1         |                        ^
cyphon_1         | SyntaxError: invalid syntax
cyphon_1         | Traceback (most recent call last):
cyphon_1         |   File "manage.py", line 26, in <module>
cyphon_1         |     execute_from_command_line(sys.argv)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
cyphon_1         |     utility.execute()
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
cyphon_1         |     settings.INSTALLED_APPS
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
cyphon_1         |     self._setup(name)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
cyphon_1         |     self._wrapped = Settings(settings_module)
cyphon_1         |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
cyphon_1         |     mod = importlib.import_module(self.SETTINGS_MODULE)
cyphon_1         |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
cyphon_1         |     return _bootstrap._gcd_import(name[level:], package, level)
cyphon_1         |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
cyphon_1         |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
cyphon_1         |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
cyphon_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
cyphon_1         |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
cyphon_1         |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
cyphon_1         |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
cyphon_1         | Error grabbing logs: invalid character 'l' after object key:value pair
^A


docker-compose logs -f nginx
ko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:35:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:36:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:37:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:38:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:39:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:40:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:41:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:42:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:43:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:44:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:45:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:46:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:47:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:48:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:49:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:50:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:51:30 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:52:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:53:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:54:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:55:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:56:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:57:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:58:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:16:59:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:00:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:01:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:02:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:03:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:04:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:05:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:06:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:07:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:08:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:09:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:10:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:11:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:12:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:13:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:14:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:15:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | 172.18.0.1 - - [16/Oct/2017:17:16:31 +0000] "GET /api/v1/monitors/enabled/ HTTP/1.1" 200 749 "http://localhost/app/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
nginx_1          | Error grabbing logs: invalid character 'l' after object key:value pair



Errors details are given below. Can you please help me to solve this.

**Comment by suchandbabu** [comment]
inginx error log from other ec2 instance where cyphondocke installed.
azonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 2017/10/23 23:31:48 [warn] 8#8: *119 upstream server temporarily disabled while connecting to upstream, client: 196.52.43.60, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 196.52.43.60 - - [23/Oct/2017:23:31:48 +0000] "GET / HTTP/1.0" 502 173 "-" "Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20100101 Firefox/31.0"
nginx_1          | 2017/10/24 00:01:03 [error] 8#8: *122 connect() failed (111: Connection refused) while connecting to upstream, client: 155.94.88.58, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 2017/10/24 00:01:03 [warn] 8#8: *122 upstream server temporarily disabled while connecting to upstream, client: 155.94.88.58, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 2017/10/24 00:01:03 [error] 8#8: *122 connect() failed (111: Connection refused) while connecting to upstream, client: 155.94.88.58, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 2017/10/24 00:01:03 [warn] 8#8: *122 upstream server temporarily disabled while connecting to upstream, client: 155.94.88.58, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 155.94.88.58 - - [24/Oct/2017:00:01:03 +0000] "GET / HTTP/1.0" 502 173 "-" "sysscan/1.0 (https://github.com/robertdavidgraham/sysscan)"
nginx_1          | 2017/10/24 06:21:57 [error] 8#8: *125 connect() failed (111: Connection refused) while connecting to upstream, client: 139.162.114.70, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "52.91.99.166"
nginx_1          | 2017/10/24 06:21:57 [warn] 8#8: *125 upstream server temporarily disabled while connecting to upstream, client: 139.162.114.70, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "52.91.99.166"
nginx_1          | 2017/10/24 06:21:57 [error] 8#8: *125 connect() failed (111: Connection refused) while connecting to upstream, client: 139.162.114.70, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "52.91.99.166"
nginx_1          | 2017/10/24 06:21:57 [warn] 8#8: *125 upstream server temporarily disabled while connecting to upstream, client: 139.162.114.70, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "52.91.99.166"
nginx_1          | 139.162.114.70 - - [24/Oct/2017:06:21:57 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
nginx_1          | 2017/10/24 08:35:17 [error] 8#8: *128 connect() failed (111: Connection refused) while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "ec2-52-91-99-166.compute-1.amazonaws.com"
nginx_1          | 2017/10/24 08:35:17 [warn] 8#8: *128 upstream server temporarily disabled while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "ec2-52-91-99-166.compute-1.amazonaws.com"
nginx_1          | 2017/10/24 08:35:17 [error] 8#8: *128 connect() failed (111: Connection refused) while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "ec2-52-91-99-166.compute-1.amazonaws.com"
nginx_1          | 2017/10/24 08:35:17 [warn] 8#8: *128 upstream server temporarily disabled while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "ec2-52-91-99-166.compute-1.amazonaws.com"
nginx_1          | 94.200.231.162 - - [24/Oct/2017:08:35:17 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
nginx_1          | 2017/10/24 08:35:18 [error] 8#8: *128 no live upstreams while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "ec2-52-91-99-166.compute-1.amazonaws.com", referrer: "http://ec2-52-91-99-166.compute-1.amazonaws.com/"
nginx_1          | 94.200.231.162 - - [24/Oct/2017:08:35:18 +0000] "GET /favicon.ico HTTP/1.1" 502 575 "http://ec2-52-91-99-166.compute-1.amazonaws.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
nginx_1          | 2017/10/24 08:35:20 [error] 8#8: *128 no live upstreams while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "ec2-52-91-99-166.compute-1.amazonaws.com"
nginx_1          | 94.200.231.162 - - [24/Oct/2017:08:35:20 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
nginx_1          | 2017/10/24 08:35:20 [error] 8#8: *128 no live upstreams while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "ec2-52-91-99-166.compute-1.amazonaws.com", referrer: "http://ec2-52-91-99-166.compute-1.amazonaws.com/"
nginx_1          | 94.200.231.162 - - [24/Oct/2017:08:35:20 +0000] "GET /favicon.ico HTTP/1.1" 502 575 "http://ec2-52-91-99-166.compute-1.amazonaws.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

**Comment by lhadjchikh** [comment]
Thanks! Can you double check your `conf.py` file for a syntax error?:
```
cyphon_1 | from .conf import *
cyphon_1 | File "/usr/src/app/cyphon/cyphon/settings/conf.py", line 19
cyphon_1 | 'ALLOWED_HOSTS': [],
cyphon_1 | ^
cyphon_1 | SyntaxError: invalid syntax
```

**Comment by lhadjchikh** [comment]
Resolved through https://github.com/dunbarcyber/cyphondock/issues/38.
