### ISSUE TITLE
Not able to access cyphon using the public domain

### ISSUE THREAD

**Issue by suchandbabu** [dunbarcyber/cyphondock#39]
Hi,
I have installed cyphondock in AWS instance. But i am not able to access the Cyphone page using the public DNS.
Its showing the 502 BAd Gateway error. 
502 Bad Gateway

nginx/1.13.5

docker-compose logs -f nginx

nginx_1          | 2017/10/23 23:31:48 [warn] 8#8: *119 upstream server temporarily disabled while connecting to upstream, client: 196.52.43.60, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 196.52.43.60 - - [23/Oct/2017:23:31:48 +0000] "GET / HTTP/1.0" 502 173 "-" "Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20100101 Firefox/31.0"
nginx_1          | 2017/10/24 00:01:03 [error] 8#8: *122 connect() failed (111: Connection refused) while connecting to upstream, client: 155.94.88.58, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 2017/10/24 00:01:03 [warn] 8#8: *122 upstream server temporarily disabled while connecting to upstream, client: 155.94.88.58, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 2017/10/24 00:01:03 [error] 8#8: *122 connect() failed (111: Connection refused) while connecting to upstream, client: 155.94.88.58, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 2017/10/24 00:01:03 [warn] 8#8: *122 upstream server temporarily disabled while connecting to upstream, client: 155.94.88.58, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8000/"
nginx_1          | 155.94.88.58 - - [24/Oct/2017:00:01:03 +0000] "GET / HTTP/1.0" 502 173 "-" "sysscan/1.0 (https://github.com/robertdavidgraham/sysscan)"
nginx_1          | 2017/10/24 06:21:57 [error] 8#8: *125 connect() failed (111: Connection refused) while connecting to upstream, client: 139.162.114.70, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "52.91.99.166"
nginx_1          | 2017/10/24 06:21:57 [warn] 8#8: *125 upstream server temporarily disabled while connecting to upstream, client: 139.162.114.70, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "52.91.99.166"
nginx_1          | 2017/10/24 06:21:57 [error] 8#8: *125 connect() failed (111: Connection refused) while connecting to upstream, client: 139.162.114.70, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "52.91.99.166"
nginx_1          | 2017/10/24 06:21:57 [warn] 8#8: *125 upstream server temporarily disabled while connecting to upstream, client: 139.162.114.70, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "52.91.99.166"
nginx_1          | 139.162.114.70 - - [24/Oct/2017:06:21:57 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
nginx_1          | 2017/10/24 08:35:17 [error] 8#8: *128 connect() failed (111: Connection refused) while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "ec2-52-91-99-166.compute-1.amazonaws.com"
nginx_1          | 2017/10/24 08:35:17 [warn] 8#8: *128 upstream server temporarily disabled while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "ec2-52-91-99-166.compute-1.amazonaws.com"
nginx_1          | 2017/10/24 08:35:17 [error] 8#8: *128 connect() failed (111: Connection refused) while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "ec2-52-91-99-166.compute-1.amazonaws.com"
nginx_1          | 2017/10/24 08:35:17 [warn] 8#8: *128 upstream server temporarily disabled while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "ec2-52-91-99-166.compute-1.amazonaws.com"
nginx_1          | 94.200.231.162 - - [24/Oct/2017:08:35:17 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
nginx_1          | 2017/10/24 08:35:18 [error] 8#8: *128 no live upstreams while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "ec2-52-91-99-166.compute-1.amazonaws.com", referrer: "http://ec2-52-91-99-166.compute-1.amazonaws.com/"
nginx_1          | 94.200.231.162 - - [24/Oct/2017:08:35:18 +0000] "GET /favicon.ico HTTP/1.1" 502 575 "http://ec2-52-91-99-166.compute-1.amazonaws.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
nginx_1          | 2017/10/24 08:35:20 [error] 8#8: *128 no live upstreams while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "ec2-52-91-99-166.compute-1.amazonaws.com"
nginx_1          | 94.200.231.162 - - [24/Oct/2017:08:35:20 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
nginx_1          | 2017/10/24 08:35:20 [error] 8#8: *128 no live upstreams while connecting to upstream, client: 94.200.231.162, server: ec2-52-91-99-166.compute-1.amazonaws.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "ec2-52-91-99-166.compute-1.amazonaws.com", referrer: "http://ec2-52-91-99-166.compute-1.amazonaws.com/"
nginx_1          | 94.200.231.162 - - [24/Oct/2017:08:35:20 +0000] "GET /favicon.ico HTTP/1.1" 502 575 "http://ec2-52-91-99-166.compute-1.amazonaws.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

**Comment by lhadjchikh** [comment]
See https://github.com/dunbarcyber/cyphondock/issues/38.
