### ISSUE TITLE
Not able to locate the incidents 

### ISSUE THREAD

**Issue by jabbarsuku** [dunbarcyber/cyphondock#45]
We are forwarding logs from Logstash to Cyphon through RabbitMQ , where can we locate this log files , do we need to write watchdog rules to create incidents in cyclops for this events ?

**Comment by lhadjchikh** [comment]
If you’re forwarding logs to a watchdogs queue, Cyphon won't save the logs, it will only generate alerts from them (although an alert will save a copy of the data that triggered it).

To save all the logs to Elasticsearch, you either need to use an Elasticsearch output plugin in your Logstash config (while still sending a copy to a RabbitMQ watchdogs queue), or output them to a datachutes queue (if you’re using Logstash to parse the logs into JSON) or a logchutes queue (if you want Cyphon to do the parsing). The default Cyphondock config for Logstash will send one copy to Elasticsearch to be saved, and another copy to a watchdogs queue for alert generation. You can view the configuration [here](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/3-output.conf).

In any case, you’ll definitely need to configure watchdogs to generate alerts that will be viewable in Cyclops.
