### ISSUE TITLE
Development Team Strength 

### ISSUE THREAD

**Issue by jabbarsuku** [dunbarcyber/cyphondock#47]
We are planning to use Cyphon in Enterprise environment, before making a call on this would like to know the following.

1. Can we contribute to active development?
2.How many developers are actually working on this Cyphon project now ?
3. Is there plan to develop it as a SIEM ?

**Comment by censey** [comment]
@jabbarsuku Thank you for your interest in Cyphon.  

1.  Yes, we encourage users to contribute to the project.
2.  Cyphon is developed by a small team within Dunbar Cybersecurity.  There are four core team members on the project but many of our other staff members contribute to the platform.
3.  We are about to launch a broader search capability in v1.6 that will provide capabilities closer to that of a typical SIEM.  That said, our goal is not to create yet another SIEM product.  We would appreciate the opportunity to gather your feedback on the current features and new capabilities we should consider for the roadmap.
