### ISSUE TITLE
Raw Log Forwarding 

### ISSUE THREAD

**Issue by jabbarsuku** [dunbarcyber/cyphondock#48]
We have a dedicated log stash instance hosted in cloud , our objective is to use this instance as a raw log aggregator and forward a copy of the logs to Cyphons integrated Logstash Instance , we were not able to do this.

We are using Filebeat for this forwarding , as Cyphon installation is using Docker , shall we do something special in Cyphons integrated Log stash to receive data from an external Logstash instance.

**Comment by darvid** [comment]
You can configure the [TCP output plugin](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-tcp.html) as an output on your dedicated Logstash and an input on the Cyphondock Logstash. 

You could also output directly to the Elasticsearch running on Cyphondock, provided the port is forwarded and accessible to your dedicated Logstash instance.

**Comment by jabbarsuku** [comment]
Does that mean forwarding using Filebeat to Logstash Instance with in Docker is not supported?

If we output directly to Elasticsearch running on  Cyphondock how will Cyphon will get a copy of it for alerts?

**Comment by darvid** [comment]
You would also need to output to RabbitMQ from your dedicated Logstash for Cyphon to generate alerts.

Forwarding Filebeats to Logstash is supported, you could certainly create a second output in your beat config to point to Cyphondock's Logstash - however, I assumed your dedicated Logstash performed filtering that Cyphondock does not, which is why you were considering Logstash to Logstash forwarding.

**Comment by jabbarsuku** [comment]
Thank you , we are not able to forward logs from dedicated Logstash  instance to Cyphondock Logstash , is there anything special we need to do for this ? 

Would it be possible for you to share a sample configuration using both tcpout and Filebeat for reference ?

**Comment by darvid** [comment]
On your dedicated Logstash, you would add an output like this:

```
output {
    tcp
    {
        host => "xxx.xxx.xxx.xxx"
        port => 1234
    }
}
```

Replace the IP address with the private address of your Cyphondock instance, and use any port you'd like, and ensure it's open in your security groups.

In the Cyphondock Logstash configuration (should be the file named ``1-input.conf``), add a corresponding input:

```
input {
    tcp
    {
        port => 1234
    }
}
```

**Comment by jabbarsuku** [comment]
Thank you
