### ISSUE TITLE
RabbitMQ to Cyphon and ES

### ISSUE THREAD

**Issue by jabbarsuku** [dunbarcyber/cyphondock#49]
As per my understanding the Logstash within Cyphon should forward a copy of the logs to RabbitMQ to be consumed by Cyphon and another set of logs to Elastic search. 

Why it is forwarding raw logs to Elasticsearch?  Is the watchdog in Cyphon is running against the Log copy in Elastic search ?

**Comment by darvid** [comment]
Cyphon's watchdogs don't store the data consumed from RabbitMQ (at least not in Elasticsearch), they simply process it for alerting purposes. A copy of the data is sent to Elasticsearch in order for Cyphon to be able to look it up later for [Contexts](https://cyphon.readthedocs.io/en/latest/user-manual/investigating-alerts.html#contexts).

**Comment by jabbarsuku** [comment]
Thanks
