### ISSUE TITLE
Logs in Cyphondock Logstash

### ISSUE THREAD

**Issue by suchandbabu** [dunbarcyber/cyphondock#51]
Hi,
I am using  Cyphondock.
Where is this Cyphondock logstash log folder exist .

Usually tail -f /var/log/logstash/* will display the status of pipeline status and forwarding logs from logstash.

But, in case of Cyphodock, there is not folder /var/log/logstash exists.  where can i find this

**Comment by darvid** [comment]
All the output from Logstash gets sent to stdout of the container, so you can simply do ``docker-compose logs -f logstash`` from within the cyphondock directory, or ``docker logs -f cyphondock_logstash_1`` from anywhere else.

**Comment by suchandbabu** [comment]
Docker-compose logs -f logstash

logstash_1 | [2017-11-12T00:48:52,064][INFO ][org.logstash.beats.BeatsHandler] Exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1, from: /94.207.134.238:48737
logstash_1 | Error grabbing logs: invalid character 'l' after object key:value pair.


I have installed TCP output plugin only in dedicated logstash instance, please let me know if I need to install same plugin on cyphondock logstash, also please help me to with the command to install logstash plugin in Docker-compose.

**Comment by jabbarsuku** [comment]
Any updates on this ?

**Comment by lhadjchikh** [comment]
Cyphondock sends container logs to the Logspout container, which sends them to Logstash, which in turns saves them to Elasticsearch — so they should be viewable in Kibana. As for installing the TCP plugin, that's unfortunately beyond our purview. I would consult Logstash or Docker docs for an answer to that one!
