### ISSUE TITLE
Elasticsearch issue 

### ISSUE THREAD

**Issue by suomikaveri** [dunbarcyber/cyphondock#54]
Hello.
I installed Cyphon on 2 separate machines via Cyphondock. However, the elasticsearch is not working on neither one of them.
I get HTTP 500-error when I try to add a collection.
Here's the main elasticsearch error: [36melasticsearch_1  |[0m Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes

Here's the nginx main error:
 [22/Nov/2017:04:59:03 +0000] "POST /admin/warehouses/collection/add/?_to_field=id&_popup=1 **HTTP/1.1" 500** 27 "http://localhost/admin/warehouses/collection/add/?_to_field=id&_popup=1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"

Is docker trying to work outside of it's container, or what is causing the issue?
I didn't have that folder mentioned. I created it, applied chmod but it still doesn't work. Nothing is being created under that folder. I'm running default settings
Java docs: "Checked exception thrown **when a file system operation is denied**, typically due to a file permission or other access check. "

**Comment by lhadjchikh** [comment]
Yes, the Elasticsearch container is trying to write to the data directory on the host. The directory needs to be writeable by the user with uid `1000` on the host (the same uid of the `elasticsearch` user in the container). Try:
```
sudo chown -R 1000:1000 /opt/cyphon/data/elasticsearch
```
See Elasticsearch's [documentation on bind-mounted configuration](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html#_b_bind_mounted_configuration) for more details.

**Comment by suomikaveri** [comment]
Thank you very much!! It solved my issue.

I did get a follow up error though. My elasticsearch warehouse was called "esDB", and error log said that it should be all lower cases. That prevented me from adding a new collection as well. I changed to lower casing and it's working well now.

**Comment by suomikaveri** [comment]
Not sure if this is Elasticsearch related, but do you know why I can't add title to my alerts?
https://i.imgur.com/Db0z6YI.png

**Comment by lhadjchikh** [comment]
Glad it worked! Thanks for the note about the warehouse name. I will add a lowercase validator to the Warehouse model to fix that.

**Comment by lhadjchikh** [comment]
As for the question about Alert titles, these are added automatically based on the "title" field associated with the Taste used for the Distillery's Container (admin/containers/container). You won't be able to add alert titles through the admin field, because it's a readonly field. But if you configure the Taste and go back and resave the Alert, it should populate the Alert title.

**Comment by lhadjchikh** [comment]
Fixed validation of Warehouse names in https://github.com/dunbarcyber/cyphon/pull/306.
