### ISSUE TITLE
Not able to update index pattern at end of install

### ISSUE THREAD

**Issue by DelFireman** [dunbarcyber/cyphondock#56]
When entering cyphon-* into the index pattern box on the last step, I get no results to select a time filter drop down box.

When I use * I get several options that populate the box.

**Comment by lhadjchikh** [comment]
That probably means the index hasn't been created yet, so you may need to save some data first. However, you can go ahead and create the index pattern for * and see what documents turn up. Just be aware that it will only search documents that have the date field you specify for the time filter.
