### ISSUE TITLE
Need help logging in

### ISSUE THREAD

**Issue by Phoenie1** [dunbarcyber/cyphondock#64]
I've transformed the VM image into AWS and installed it.  What's the bloody root password?

**Comment by darvid** [comment]
How old is the VM image you're using? Was it the OVA, or did you use the more recent ISO installer?

On the OVA, the username is ``user`` and the password is ``P@$$w0rd123``. With the newer installer ISO, you are prompted to create a set of credentials. Both are Ubuntu based, and as such, you cannot login as root from a tty, and to escalate to root from an unprivileged user, you would simply use ``sudo`` and provide your user password.

Hope that helps.

**Comment by Phoenie1** [comment]
That did, thank you.  I couldn't find the credentials anywhere in the documentation.
