### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by santi10** [dunbarcyber/cyphondock#66]
Hi,

I've just configured Cyphon. I try config the mailbox and when I sett on "Get new mail" received this message "Sever Error 500".

Do you help me about this issue, please?

Regards

**Comment by chasepbrewer** [comment]
This could potentially be a duplicate of issue #37. Check that issue first to see if the error matches yours. If not, please check the logs of both the nginx and cyphon containers by running these commands in the cyphondock repository:

```
docker-compose logs -f nginx
docker-compose logs -f cyphon
```

Paste any errors you find here.

**Comment by santi10** [comment]
Fixed, Thanks a lot
