### ISSUE TITLE
Alert co-relation 

### ISSUE THREAD

**Issue by sajeeshgit** [dunbarcyber/cyphondock#67]
Hi Team,

I am looking a way to co-relate two or three events and if two out of three events are true then generate an alert, Is that possible ? 

Example : 

Events can be considered as emails here, if I have two or three emails which are of subject "abc high" , coming from different sender / source, which is triggered in >1min . Can we check all this and co-relate those two/n emails and then generate an alert on top of this. 

The Idea here is to make a precise alerting mechanism, if we have n number of alerts coming from different sources compare them and output a single alert ( after doing the validations )

Please let me know.

Thank you.
Sajeesh.

**Comment by fatalglitch** [comment]
I would suggest making this feature request on the Cyphon project page. https://github.com/dunbarcyber/cyphon

This repo is mainly for the Cyphon Docker build which allows quick stand up of an functional environment for evaluation
