### ISSUE TITLE
When an email with attachment is send, it keeps on creating duplicate emails in "Email messages"

### ISSUE THREAD

**Issue by sajeeshgit** [dunbarcyber/cyphondock#69]
Hi,

When I send a mail with attachment and when I check the "Email messages" section on cyphon, I could see duplicate emails created twice every minute with the same subject name. 
<img width="789" alt="screen shot 2018-03-30 at 3 25 17 am" src="https://user-images.githubusercontent.com/18749401/38115534-08094058-33ca-11e8-9858-2b59bdfc1c29.png">

I have uploaded the SS, I there a possible solution for this issue?

**Comment by lhadjchikh** [comment]
Hi @sajeeshgit, this can happen when the Celery task is not able to empty the inbox before the next task interval starts. Try increasing the interval in your [config/cyphon/settings/base.py](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/cyphon/settings/base.py#L313-L316) file to see if that resolves the issue, e.g.:
```
CELERYBEAT_SCHEDULE = {
    'get-new-mail': {
        'task': 'tasks.get_new_mail',
        'schedule': timedelta(seconds=60)
    },
    ...
}
```

**Comment by sajeeshgit** [comment]
@lhadjchikh thank you for the response, I solved the issue by deleting the mail with attachment at the source; reason for doing this was I want the mail fetch intervals as minimum as possible.

**Comment by lhadjchikh** [comment]
Ok. You might want to double check your settings, though, to make sure the attachment was allowed:

**Comment by lhadjchikh** [comment]
``
