### ISSUE TITLE
Can we compare two different emails

### ISSUE THREAD

**Issue by sajeeshgit** [dunbarcyber/cyphondock#71]
Hi team,

A quick question, can we compare two emails with the same subject but coming in a different time stamp. Need to compare few strings in the content of both the emails( of same subject ) and then generate an alert. Please let me know.

Thanks.

**Comment by chasepbrewer** [comment]
Duplicate of dunbarcyber/cyphon#484

Closing here while we track the progress of that feature over in the other repository.
