### ISSUE TITLE
cyphon [CRITICAL] WORKER TIMEOUT

### ISSUE THREAD

**Issue by santi10** [dunbarcyber/cyphondock#73]
Hi,

I'm seening this message "cyphon [CRITICAL] WORKER TIMEOUT", do you know this message, please????

Thx

**Comment by chasepbrewer** [comment]
It means that the service connecting Django to the Nginx server timed out. What do the logs around the time of that error say? `docker-compose logs -f -t`

**Comment by santi10** [comment]
HI, I see this log "ValueError: Unable to configure handler 'file': [Errno 13] Permission denied: '/usr/src/app/cyphon/django.log'"...could you have any idea about this?

Regards

**Comment by fatalglitch** [comment]
Closing issue due to age. If you are still encountering issues please let us know.
