### ISSUE TITLE
don't see alert on dashboard

### ISSUE THREAD

**Issue by santi10** [dunbarcyber/cyphondock#74]
Hi Folk,

I'm having several issues with cyphon, I think that my config is fine, my site is:

- Source sent to udp port 5044 to Cyphon (cyphondock).
Logs Cyphon: cyphon_1         | Running Production Server
- Logstash conf like input, filter and output
Logs Logstash: 
logstash_1       | [2018-04-02T14:50:31,359][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
logstash_1       | [2018-04-02T14:50:31,444][WARN ][logstash.inputs.beats    ] WARNING! - Multiline codec with beats input has been deprecated. Support for this configuration will be removed in a future version. Please refer to the beats documentation for how to best manage multiline data. See https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html
logstash_1       | [2018-04-02T14:50:31,452][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5045"}
logstash_1       | [2018-04-02T14:50:31,473][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"0.0.0.0:5046"}
logstash_1       | [2018-04-02T14:50:31,475][INFO ][org.logstash.beats.Server] Starting server on port: 5045
logstash_1       | [2018-04-02T14:50:31,478][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"0.0.0.0:5000"}
logstash_1       | [2018-04-02T14:50:31,477][INFO ][org.logstash.beats.Server] Starting server on port: 5044
logstash_1       | [2018-04-02T14:50:31,491][INFO ][logstash.inputs.udp      ] UDP listener started {:address=>"0.0.0.0:5046", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
logstash_1       | [2018-04-02T14:50:31,491][INFO ][logstash.inputs.udp      ] UDP listener started {:address=>"0.0.0.0:5000", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
logstash_1       | [2018-04-02T14:50:31,518][INFO ][logstash.pipeline        ] Pipeline main started

- Elasticsearach and kibana are up.

I see with tcpdump on Cyphon machine the events and good port. 

Do I have restart the services but show the events on Cyphon and Kibana????
What I must do but that it is work?

Regards

**Comment by chasepbrewer** [comment]
Did you setup your data structure in Cyphon? Documentation on that is found here: http://cyphon.readthedocs.io/en/latest/tutorials/logstash-tutorial.html#step-3-cyphon

**Comment by santi10** [comment]
Yes, I set this tutorial but I don't see nothing. Do you think to must restart the machine?

Regards

**Comment by santi10** [comment]
Also I've created a new alert via portal admin, this alert I'm looking on dashboar Cyphon but I don't see on Kibana. The index "Cyphon" isn't unvalible, I see logspout and watcher only...what I can do, please?

Thanks!

**Comment by fatalglitch** [comment]
alerts are not stored in elasticsearch, and thus not visible via Kibana. Alerts are stored in the postgres database.

What beat clients do you have running pointed at port 5044? 5044 is used for the Elastic Beats agents, ie. filebeat, winlogbeat, metricbeat, etc. Any other data types being pointed at port 5044 will be dropped due to not being properly formatted.

**Comment by santi10** [comment]
Hi, I'm seending logs vi another port like 5046. I have pharser the logs on logstash (can see on kibana properly). Do you say me that Cyphon not lisen on another port ????

I don't see the alerts on Cyphon, I've followed this FAQ "http://cyphon.readthedocs.io/en/latest/tutorials/logstash-tutorial.html#"

Thanks

**Comment by santi10** [comment]
What i can do what I see the logs into Cyphon???

The logs of Cyphon is:

user@Cyphon02:/opt/cyphon/cyphondock$ docker-compose logs -f cyphon
Attaching to cyphondock_cyphon_1
cyphon_1         | Running Production Server

Cyphon seems is working fine because I see the dashboard and I've created a new alert and all is ok.

Any help for me, please!

**Comment by fatalglitch** [comment]
Please read through the tutorial again. The tutorial is specifically designed with ports in mind, changing the ports or pieces of the tutorial require a more thorough understanding of the underlying concepts of setup.

The alerts to Cyphon are fed through rabbitmq, which are consumed by the watchdog into Cyphon. If you don't have all the components setup, you won't be seeing alerts.

Cyphon is not for Log Management, you keep mentioning "I don't see the logs". The only items that you should be feeding into Cyphon are the events that require alerting. In the example, snort alerts are being sent into logstash, which then parses the alert events, and feeds them through to RabbitMQ.
