### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by santi10** [dunbarcyber/cyphondock#75]
Hi,

I`m running cyphondock and I show this error 502. 

The logs of cyphon is:
cyphon_1         | Running Production Server

The logs of nginx is:
nginx_1          | 2018/04/09 23:17:06 [error] 7#7: *455 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.11.139, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:8000/", host: "192.168.11.179"

what I can do it, please???

Thx

**Comment by fatalglitch** [comment]
Please provide the output of ```docker ps```

Have you made any changes or customizations to the docker-compose files?

**Comment by santi10** [comment]
The container Nginx has been a long time..
