### ISSUE TITLE
logstash container won't start (cant find logstash.yml)

### ISSUE THREAD

**Issue by adamstauffer** [dunbarcyber/cyphondock#8]
When starting the production docker-compose, the logstash container constantly crashes because it can't find logstash.yml

```
$ docker logs -f cyphondock_logstash_1
2017/05/10 22:13:38 error: open /usr/share/logstash/config/logstash.yml: no such file or directory
```

this is volumed in the docker-compose.yml at [L126](https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.yml#L126), however there is no config/logstash/config

touching a blank config file in my config/logstash/config seems to work for me, i.e.

```
$ touch config/logstash/config/logstash.yml
```

all of the defaults should be functional per the [logstash docs](https://www.elastic.co/guide/en/logstash/5.3/logstash-settings-file.html) but maybe we can trade notes in case there is something special needed

**Comment by lhadjchikh** [comment]
Sorry, `.gitignore` was ignoring that directory by mistake. Should be fixed now. You'll need to copy the files from `config-COPYME/logstash/config` into your new `config/logstash/config` folder. Thanks for catching that!

The only change to the `logstash.yml` from the defaults is to set `xpack.monitoring.enabled: false`, so things don't break if you don't have an X-Pack subscription. This is also done in `elasticsearch.yml` and `kibana.yml`.

**Comment by adamstauffer** [comment]
thanks!

**Comment by lhadjchikh** [comment]
Actually, I double checked, and the X-Pack setting is apparently only needed in `elasticsearch.yml` and `kibana.yml`, so you're right! Logstash defaults should work, so I will get rid of that setting. :-)
